#!/usr/bin/env node
/**
 * Test runner. Wired up as `npm test`.
 *
 * Re-runs the workload on the current skill state, regenerates the
 * optimized session JSONL, runs the deterministic measurement, and
 * asserts the reduction is >= 30%. The baseline session is committed
 * and never regenerated by this script (it is the reference).
 *
 * The harness is identical to the one used to capture the baseline.
 * Token counts come from the cl100k_base-compatible tokenizer, not
 * from the model.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const SESSIONS_DIR = path.join(REPO_ROOT, 'sessions');
const BASELINE = path.join(SESSIONS_DIR, 'baseline_session.jsonl');
const OPTIMIZED = path.join(SESSIONS_DIR, 'optimized_session.jsonl');

function run(cmd, args) {
  return execFileSync(cmd, args, { encoding: 'utf8', cwd: REPO_ROOT });
}

function mustExist(file) {
  if (!fs.existsSync(file)) {
    process.stderr.write(`[test] missing file: ${file}\n`);
    process.exit(1);
  }
}

function main() {
  mustExist(BASELINE);

  // Regenerate the optimized session on the current skill state.
  // variant=slim drives the .apm/slim-skills/ set; the baseline session
  // was captured from the original .apm/skills/ set (byte-identical
  // to origin/main) and is committed in the repo.
  run('node', ['tools/workload.mjs', OPTIMIZED, 'slim']);

  // Run the deterministic measurement.
  const output = run('node', ['tools/measure.mjs', BASELINE, OPTIMIZED]);
  process.stdout.write(output);

  // Parse the reduction from the measurement output.
  const match = output.match(/reduction:\s+([\d.]+)%/);
  if (!match) {
    process.stderr.write('[test] could not parse reduction from measure output\n');
    process.exit(1);
  }
  const reductionPct = parseFloat(match[1]);
  const targetPct = 30;

  if (reductionPct >= targetPct) {
    process.stdout.write(
      `[test] PASS: ${reductionPct}% reduction >= ${targetPct}% target\n`,
    );
    process.exit(0);
  } else {
    process.stderr.write(
      `[test] FAIL: ${reductionPct}% reduction < ${targetPct}% target\n`,
    );
    process.exit(1);
  }
}

main();
